### PR TITLE
Fixed a crash that occured when rapidly switching tabs.

### PR DESCRIPTION
**Pull request by retendo**
That should auto-dispose the subscription as soon as the ranked players view vanishes from screen.

### CODE REVIEW

**Comment by richeterre** [comment]
Good catch! However, couldn't it be solved even more elegantly by something similar to b1d47488d0f88c71f489dcfb747f26df4bab6749? To be honest, I made that fix more for style reasons, but `switchToLatest` should take care of disposal nicely there.

**Comment by retendo** [comment]
Yep, that makes more sense. My "fix" didn't only prevent the crash, but also the implemented functionality of fetching ranked players. For some reason the takeUntil method doesn't seem to do what I expected, at least not in this case, as the subscribe block is never called.

Changed it to match the style of the MatchesViewModel

**Comment by richeterre** [comment]
Exactly, now that you say it I too realized that it fetches them only once and then stops. That's because `refreshSignal` actually terminates when the view becomes inactive due to the `takeUntil:` and as you're setting in up in the initializer, it will not get redefined, so the subscribe block will indeed not be called afterwards.

**Comment by retendo** [comment]
That's what I expected but when I tested it, it wasn't called even once. I put a breakpoint in the subscribeNext: block and it never stopped there.

**Pull request merged**
